services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: mysecretpassword123
      POSTGRES_DB: habit_hero
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build: ./backend
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/code
    depends_on:
      - db

volumes:
  postgres_data: