"""Add category and start_date to habits

Revision ID: df8c05fe960f
Revises: 
Create Date: 2025-10-19 18:09:51.711455

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df8c05fe960f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('habits', sa.Column('category', sa.String(), nullable=False))
    op.add_column('habits', sa.Column('start_date', sa.Date(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('habits', 'start_date')
    op.drop_column('habits', 'category')
    # ### end Alembic commands ###
